core/urls.py
import django
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webplayground.urls')),
    path('pages/',include('pages.urls')),

    #Path auth
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('registration.urls')),
]

pages/urls.py
from django.urls import path
from .views import PageDelete, PageListView,PageDetailView,PageCreate,PageUpdate

app_name='pages'

urlpatterns = [
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:slug>/', PageDetailView.as_view(), name='page'),
    path('create/',PageCreate.as_view(),name='create'),
    path('update/<int:pk>',PageUpdate.as_view(), name='update'),
    path('delete/<int:pk>',PageDelete.as_view(), name='delete'),
    
    
    
]

registration/urls.py
import imp
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup',SignUpView.as_view(),name='signup'),
]

webplayground/urls.py
from django.urls import path
from .views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

webplayground/models.py
from django.db import models

# Create your models here.

pages/forms.py
from tkinter import Widget
from django import forms
from .models import Page

class PageForm(forms.ModelForm):
    
    class Meta:
        model =Page
        fields = ['title','content','order']
        widgets ={
            'title': forms.TextInput(attrs={'class':'form-control','placeholder':'Título'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'order':forms.NumberInput(attrs={'class':'form-control'}),
        }

        #Para que no salga los nombres en la pagina
        labels={
            'title':'',
            'content':'',
            'order':'',
        }

pages/views.py
from .models import Page

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .forms import PageForm

from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

class StaffRequiredMixin(object):
    """    Este mixin requerira que el usuario sea miembro del staff
    """
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        #Es lo mismo que tener : staff_member_required|||
        #if not request.user.is_staff:
            #return redirect(reverse_lazy('admin:login'))
        return super(StaffRequiredMixin,self).dispatch(request, *args, **kwargs)

# ListView
class PageListView(ListView):
    model = Page

#DetailView
class PageDetailView(DetailView):
    model = Page

#CreateView
@method_decorator(staff_member_required,name="dispatch")
class PageCreate(CreateView):
    model = Page
    form_class = PageForm
    success_url = reverse_lazy('pages:pages')


#UpdateView
class PageUpdate(StaffRequiredMixin,UpdateView):
    model = Page
    form_class = PageForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('pages:update',args=[self.object.id]) + '?ok'

#DeleteView    
class PageDelete(StaffRequiredMixin,DeleteView):
    model = Page
    success_url = reverse_lazy('pages:pages')

webplayground/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name= "webplayground/home.html"
    
class SamplePageView(TemplateView):
    template_name = "webplayground/sample.html"

pages/templates/pages/page_confirm_delete.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/pages_menu.html'%}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
            <div class="col-md-9 mx-auto">
                <div>
                    <form action="" method="post">{% csrf_token %}
                        <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
                        <input type="submit" class="btn btn-danger btn-block" value="Sí,Borrar página" />
                    </form>
                </div>
            </div>
            </div>
        </div>
    </main>
{% endblock %}

pages/templates/pages/page_detail.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
{% include 'pages/pages_menu.html' %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{object.title}}</h2>
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'pages:update' object.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_form.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
{% include 'pages/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-4">
      <div class="col-md-9 mx-auto">
        
        <form action="" method="post">{% csrf_token %}
          {{ form.as_p }}
          <div class="text-center">
            <input type="submit" class="btn btn-primary btn-block" value="Crear página" />
          </div>
        </form>
        
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_list.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
{% include 'pages/pages_menu.html' %}
<main role="main">
  <div class="container mb-4">
    {% for page in object_list|dictsort:'id' reversed %}
      <div class="row mt-3">
        <div class="col-md-9 mx-auto">
          <h2 class="mb-4">{{page.title}}</h2>
          <div>
            <p>{{page.content|striptags|safe|truncatechars:"200"}}</p>
            <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más |</a>
              
              {% if request.user.is_staff %}
                <a href="{% url 'pages:update' page.id %}">Editar |</a>
                <a href="{% url 'pages:delete' page.id %}">Eliminar</a>
              {% endif %}
              
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

pages/templates/pages/page_update_form.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
{% include 'pages/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style="color:rgb(204, 207, 23);">
              Pagina editada correctamente.
              <a href="{% url 'pages:page' page.id page.title|slugify %}">Haz click aqui para ver el resultado</a>
            </p>
          {% endif %}
          <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
              <input type="submit" class="btn btn-primary btn-block" value="Actualizar página" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/pages_menu.html
<!--Ckeditor fuera del administrador de django -->
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'pages/css/custom_ckeditor.css' %}" rel="stylesheet">
<!--end Ckeditor-->

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:create' %}"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

webplayground/templates/webplayground/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'webplayground/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'webplayground/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'webplayground/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Playground</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:pages' %}">Páginas</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href=" {% url 'login' %}">Acceder</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href=" {% url 'signup' %}">Registro</a>
                </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Salir</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'webplayground/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'webplayground/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'webplayground/js/main.js' %}"></script>
  </body>
</html>

webplayground/templates/webplayground/home.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
  <div class="container">
    <div style="padding-top:50px; text-align:center;">
      <h1>Web Playground</h1>
      <p class="lead">CBV, autenticación, registros, perfiles y más</p>
    </div>
  </div>
{% endblock %}

webplayground/templates/webplayground/sample.html
{% extends 'webplayground/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'webplayground/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>123456Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}